# Cpp language
language: cpp
dist: bionic

# Compiler selection
compiler:
  - clang
  - gcc

# Apt packages
addons:
  apt:
    sources:
      - sourceline: "ppa:beineri/opt-qt-5.12.3-bionic"
    packages:
      - g++-8
      - gcc-8
      - libgl1-mesa-dev
      - qt512base
      - qt512multimedia

# Install
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
  - source /opt/qt512/bin/qt512-env.sh # Needed with Beineri PPA

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install
  - make -j2
  - make install
