# Cpp language
language: cpp
sudo: required
dist: trusty

# Compiler selection
compiler:
  - clang
  - gcc
# Enable caching
cache:
  apt: true
# Build matrix
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
        - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    packages:
        - g++-7
        - gcc-7
        - libpthread-stubs0-dev
        #- qt5-default
        #- libqt5opengl5-dev
        #- qtmultimedia5-dev
        # Above replaced by below for Beineri PPA
        - qt510base
        - qt510multimedia
# Install
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - source /opt/qt510/bin/qt510-env.sh # Needed with Beineri PPA

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
