version: '0.0.0.{build}'

image: Visual Studio 2017

environment:
  matrix:
  - ARCHITECTURE: "x86"
    QT5_DIR: C:\Qt\5.11\msvc2015 # There is no msvc2017
  - ARCHITECTURE: "x64"
    QT5_DIR: C:\Qt\5.11\msvc2017_64

matrix:
  fast_finish: true

install:
- call "%QT5_DIR%\bin\qtenv2.bat"
- call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat" %ARCHITECTURE%
- cd /D "%APPVEYOR_BUILD_FOLDER%"
- git submodule update --init --recursive

before_build:
- cmake -H. -Bbuild -G Ninja -DCMAKE_PREFIX_PATH="%QT5_DIR%" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DCMAKE_MAKE_PROGRAM="C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja\\ninja.exe"

build_script:
- cmake --build build --target install

after_build:
- 7z a libbndl-%ARCHITECTURE%-release.zip install\*

test: off

artifacts:
- path: install\libbndl-%ARCHITECTURE%-release.zip
