version: '0.0.0.{build}'

image: Visual Studio 2017

environment:
  matrix:
  - ARCHITECTURE: "x86"
    QT5_DIR: C:\Qt\5.12\msvc2017
  - ARCHITECTURE: "x64"
    QT5_DIR: C:\Qt\5.12\msvc2017_64

matrix:
  fast_finish: true

install:
- call "%QT5_DIR%\bin\qtenv2.bat"
- call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat" %ARCHITECTURE%
- cd /D "%APPVEYOR_BUILD_FOLDER%"
- git submodule update --init --recursive

before_build:
- cmake -H. -Bbuild-debug -G Ninja -DCMAKE_PREFIX_PATH="%QT5_DIR%" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install-debug -DCMAKE_MAKE_PROGRAM="C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja\\ninja.exe"
- cmake -H. -Bbuild-release -G Ninja -DCMAKE_PREFIX_PATH="%QT5_DIR%" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install-release -DCMAKE_MAKE_PROGRAM="C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja\\ninja.exe"


build_script:
- cmake --build build-debug --target install
- cmake --build build-release --target install

after_build:
- cd install-debug
- 7z a libbndl-%ARCHITECTURE%-debug.zip .\*
- cd ..\install-release
- 7z a libbndl-%ARCHITECTURE%-release.zip .\*

test: off

artifacts:
- path: install-release\libbndl-%ARCHITECTURE%-release.zip
  name: libbndl-%ARCHITECTURE%-release.zip
- path: install-debug\libbndl-%ARCHITECTURE%-debug.zip
  name: libbndl-%ARCHITECTURE%-debug.zip
